In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [75]:
df=pd.read_csv("..//Data/bank.csv")

In [76]:
df = df.rename(columns={'oldbalanceOrg': 'oldbalanceOrig'})

To match the names, been having typo erros since one have Org and other have Orig

In [77]:
df['full_amount'] = (df['amount'] == df['oldbalanceOrig'])

created boolean feature indicate the amount equals to the available fund in original account

In [78]:
df['ODest_less_amount'] = (df['amount'] >= df['oldbalanceDest'])

created boolean feature indicate the amount greater than or equal to the original balance of destination account

In [84]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrig,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,full_amount,ODest_less_amount
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0,False,True
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0,False,True
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0,True,True
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0,True,False
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0,False,True
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0,False,True
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0,False,True
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0,False,True
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0,False,True
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0,False,False

In [80]:
dfn=df.drop(columns=['step','nameOrig','nameDest','oldbalanceDest','newbalanceDest','isFlaggedFraud'])

Removed step and ids and isFlaggedFraud which have no direct relation to Fraud detection.
Removed oldbalanceDest, newbalanceDest.

In [81]:
dfn.head()

,type,amount,oldbalanceOrig,newbalanceOrig,isFraud,full_amount,ODest_less_amount
0,PAYMENT,9839.64,170136.0,160296.36,0,False,True
1,PAYMENT,1864.28,21249.0,19384.72,0,False,True
2,TRANSFER,181.00,181.0,0.00,1,True,True
3,CASH_OUT,181.00,181.0,0.00,1,True,False
4,PAYMENT,11668.14,41554.0,29885.86,0,False,True

In [82]:
dfn=pd.get_dummies(data=dfn,columns=['type'])

In [83]:
dfn.to_csv('../Data/bank_cleaned.csv', index=False)